name: Build

on:
  push:
    branches: [ main, cmake-configurator ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        
    - name: Install ARM GNU Toolchain
      run: |
        $url = "https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v13.2.1-1.1/xpack-arm-none-eabi-gcc-13.2.1-1.1-win32-x64.zip"
        $output = "arm-toolchain.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath "C:\arm-toolchain"
        echo "C:\arm-toolchain\xpack-arm-none-eabi-gcc-13.2.1-1.1\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Install Pico SDK 2.1.1 manually
      run: |
        git clone -b 2.1.1 --depth 1 https://github.com/raspberrypi/pico-sdk.git pico-sdk
        cd pico-sdk
        git submodule update --init
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DPICO_SDK_PATH=../pico-sdk -DPICO_BOARD_HEADER_DIRS="../src/boards" -DPICO_BOARD=pico9918
        
    - name: Debug available targets
      run: |
        cd build
        ninja -t targets | findstr -v "phony" | head -20
        
    - name: Build default target
      run: |
        cd build
        cmake --build .
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pico9918-windows
        path: |
          build/dist/*.uf2
          build/dist/*.rom
          build/dist/*.bin
          build/dist/*.nabu
          build/dist/*.npz

  build-linux:
    runs-on: ubuntu-latest
    name: Linux Build
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3 python3-pip git gcc-arm-none-eabi
        pip3 install pillow
        
    - name: Install Pico SDK 2.1.1 manually
      run: |
        git clone -b 2.1.1 --depth 1 https://github.com/raspberrypi/pico-sdk.git pico-sdk
        cd pico-sdk
        git submodule update --init
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DPICO_SDK_PATH=../pico-sdk -DPICO_BOARD_HEADER_DIRS="../src/boards" -DPICO_BOARD=pico9918
        
    - name: Debug available targets
      run: |
        cd build
        ninja -t targets | findstr -v "phony" | head -20
        
    - name: Build default target
      run: |
        cd build
        cmake --build .
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pico9918-linux
        path: |
          build/dist/*.uf2
          build/dist/*.rom
          build/dist/*.bin
          build/dist/*.nabu
          build/dist/*.npz